#!/bin/bash
# ci_post_clone.sh — Xcode Cloud post-clone hook (must finish within 10 min).
#
# WHY THIS EXISTS
# iOS plugins are integrated via Swift Package Manager through the LOCAL package
# ios/Flutter/ephemeral/Packages/FlutterGeneratedPluginSwiftPackage. That
# package is GENERATED by the Flutter tool and gitignored, so on a fresh
# Xcode Cloud clone `xcodebuild archive` dies after ~30 s with:
#   "Could not resolve package dependencies: ... FlutterGeneratedPluginSwiftPackage
#    doesn't exist in file system"
# (this killed Archive builds 1 and 2 on 2026-08-16).
# This script installs the pinned Flutter SDK and generates everything
# xcodebuild needs (--config-only = configure + generate, no app compilation).
#
# Keep FLUTTER_VERSION in sync with `flutter-version` in .github/workflows/ci.yml.
set -euo pipefail

FLUTTER_VERSION=3.44.8
FLUTTER_ZIP="https://storage.googleapis.com/flutter_infra_release/releases/stable/macos/flutter_macos_${FLUTTER_VERSION}-stable.zip"

cd "${CI_WORKSPACE:-$(cd "$(dirname "$0")/.." && pwd)}"

# Fresh VM per build: the SDK download is NOT cached by Xcode Cloud (~2-4 min).
# Only unzip when absent so a re-run within the same build is cheap.
if [ ! -x ./flutter/bin/flutter ]; then
  echo "Installing Flutter ${FLUTTER_VERSION} into ./flutter"
  curl -fL --retry 3 "$FLUTTER_ZIP" -o /tmp/flutter.zip
  unzip -q /tmp/flutter.zip -d .
  rm -f /tmp/flutter.zip
fi

export PATH="$PWD/flutter/bin:$PATH"
export FLUTTER_SUPPRESS_ANALYTICS=true

flutter --version
flutter pub get
# Generates Flutter/Generated.xcconfig AND the SPM package tree xcodebuild resolves.
flutter build ios --config-only --release

# Fail here with a clear message instead of a cryptic SPM error later.
if [ ! -d ios/Flutter/ephemeral/Packages/FlutterGeneratedPluginSwiftPackage ]; then
  echo "ERROR: ios/Flutter/ephemeral/Packages/FlutterGeneratedPluginSwiftPackage was not generated"
  exit 1
fi
echo "OK: iOS project configured — xcodebuild can resolve FlutterGeneratedPluginSwiftPackage"
