// Mocks generated by Mockito 5.4.6 from annotations
// in mamadera/test/features/menu/presentation/widgets/baby_profile_section_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mamadera/features/baby/domain/repositories/baby_profile_repository.dart'
    as _i2;
import 'package:mamadera/shared/domain/entities/baby_profile.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [BabyProfileRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockBabyProfileRepository extends _i1.Mock
    implements _i2.BabyProfileRepository {
  @override
  _i3.Future<List<_i4.BabyProfile>> getAllProfiles() => (super.noSuchMethod(
        Invocation.method(
          #getAllProfiles,
          [],
        ),
        returnValue:
            _i3.Future<List<_i4.BabyProfile>>.value(<_i4.BabyProfile>[]),
        returnValueForMissingStub:
            _i3.Future<List<_i4.BabyProfile>>.value(<_i4.BabyProfile>[]),
      ) as _i3.Future<List<_i4.BabyProfile>>);

  @override
  _i3.Future<_i4.BabyProfile?> getActiveProfile() => (super.noSuchMethod(
        Invocation.method(
          #getActiveProfile,
          [],
        ),
        returnValue: _i3.Future<_i4.BabyProfile?>.value(),
        returnValueForMissingStub: _i3.Future<_i4.BabyProfile?>.value(),
      ) as _i3.Future<_i4.BabyProfile?>);

  @override
  _i3.Future<String> insertProfile(_i4.BabyProfile? profile) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertProfile,
          [profile],
        ),
        returnValue: _i3.Future<String>.value(_i5.dummyValue<String>(
          this,
          Invocation.method(
            #insertProfile,
            [profile],
          ),
        )),
        returnValueForMissingStub:
            _i3.Future<String>.value(_i5.dummyValue<String>(
          this,
          Invocation.method(
            #insertProfile,
            [profile],
          ),
        )),
      ) as _i3.Future<String>);

  @override
  _i3.Future<_i4.BabyProfile?> updateProfile(
    String? id, {
    String? name,
    DateTime? birthDate,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateProfile,
          [id],
          {
            #name: name,
            #birthDate: birthDate,
          },
        ),
        returnValue: _i3.Future<_i4.BabyProfile?>.value(),
        returnValueForMissingStub: _i3.Future<_i4.BabyProfile?>.value(),
      ) as _i3.Future<_i4.BabyProfile?>);

  @override
  _i3.Future<bool> deleteProfile(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteProfile,
          [id],
        ),
        returnValue: _i3.Future<bool>.value(false),
        returnValueForMissingStub: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<void> setActiveProfile(String? id) => (super.noSuchMethod(
        Invocation.method(
          #setActiveProfile,
          [id],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
