// Mocks generated by Mockito 5.4.6 from annotations
// in mamadera/test/features/home/presentation/screens/home_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mamadera/features/home/domain/repositories/tracking_repository.dart'
    as _i2;
import 'package:mamadera/shared/domain/entities/tracking_enums.dart' as _i6;
import 'package:mamadera/shared/domain/entities/tracking_event.dart' as _i4;
import 'package:mamadera/shared/domain/entities/tracking_type.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [TrackingRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTrackingRepository extends _i1.Mock
    implements _i2.TrackingRepository {
  @override
  _i3.Future<List<_i4.TrackingEvent>> getAllEventsOrdered() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllEventsOrdered,
          [],
        ),
        returnValue:
            _i3.Future<List<_i4.TrackingEvent>>.value(<_i4.TrackingEvent>[]),
        returnValueForMissingStub:
            _i3.Future<List<_i4.TrackingEvent>>.value(<_i4.TrackingEvent>[]),
      ) as _i3.Future<List<_i4.TrackingEvent>>);

  @override
  _i3.Future<List<_i4.TrackingEvent>> getEventsByType(_i5.TrackingType? type) =>
      (super.noSuchMethod(
        Invocation.method(
          #getEventsByType,
          [type],
        ),
        returnValue:
            _i3.Future<List<_i4.TrackingEvent>>.value(<_i4.TrackingEvent>[]),
        returnValueForMissingStub:
            _i3.Future<List<_i4.TrackingEvent>>.value(<_i4.TrackingEvent>[]),
      ) as _i3.Future<List<_i4.TrackingEvent>>);

  @override
  _i3.Future<int> insertEvent({
    required _i5.TrackingType? type,
    DateTime? timestamp,
    double? duration,
    String? notes,
    _i6.WasteType? wasteType,
    _i6.PipiColor? pipiColor,
    _i6.CacaColor? cacaColor,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertEvent,
          [],
          {
            #type: type,
            #timestamp: timestamp,
            #duration: duration,
            #notes: notes,
            #wasteType: wasteType,
            #pipiColor: pipiColor,
            #cacaColor: cacaColor,
          },
        ),
        returnValue: _i3.Future<int>.value(0),
        returnValueForMissingStub: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);
}
